### ISSUE TITLE
Dockerfile for nvidia gpus on arm64 based hardware.

### ISSUE THREAD

**Issue by philcanman** [breuner/elbencho#45]
I am looking for a arm64 based elbencho with gpu (nvidia/cuda) support.  

Would one of these containers work?
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nvhpc/tags

**Comment by breuner** [comment]
Hi @philcanman ,

thanks for asking. Seems like it's really about time to add a container with multi-platform support that can also be used with GPUs on ARM64.

Based on your request I'm now working on a new container that should appear under the tag "master-ubuntu-cuda-multiarch" (always based on the latest available cuda version at the time when the container is built) in the elbencho docker hub repo either tonight or tomorrow.
If you're specifically interested in the Dockerfile (because you mentioned that in the subject) to build the container yourself then you'll find that under `build_helpers/docker/Dockerfile.ubuntu-cuda-multiarch.local` when the container build succeeds.

I don't have an ARM-based GPU host available to test with at the moment (but hopefully soon), so there is a small risk that the container doesn't work and thus I would very much appreciate feedback.

**Comment by philcanman** [comment]
I can confirm that the new dockerfile does build on a arm host without errors.
<img width="815" alt="image" src="https://github.com/breuner/elbencho/assets/8276820/b43e4a87-900e-4d7f-8a13-8d6d36e55e7c">

**Comment by breuner** [comment]
Thanks for the confirmation, @philcanman
