### ISSUE TITLE
Delete directories not working

### ISSUE THREAD

**Issue by alexandrestein** [breuner/elbencho#5]
I'm evaluating this package and I still very new to it.

But it looks like I found a bug around the cleanup after bench is done.
Here is a screenshot of the script and the output.

Thank you for this package and all the efforts.
![Screenshot from 2021-01-04 13-04-53](https://user-images.githubusercontent.com/5431025/103533820-19cb2b80-4e8e-11eb-852b-8c95b42c9078.png)

**Comment by breuner** [comment]
Hi @alexandrestein, it looks like the parameter "-F"/"--delfiles" is missing to delete the created files before "-D" tries to delete the created directories.

Just as an additional hint: In case you ever need to delete a partially created dataset (e.g. because you pressed CTRL+C during the creation phase) then you can also add the additional option "--nodelerr" so that elbencho won't complain when some of the expected files are missing.

Please let me know if this helped, so that I can close this issue.

**Comment by alexandrestein** [comment]
Hi,

Thank you very much.
It solved it, sorry for the noise...

I will test this package during the next days and may come back with similar misused. :worried: 

This can be closed.
Thanks again.
